sugar:
  image: absolutapps/stack-php55-oracle

  volumes:
   - ./sugar:/var/www/html/sugar
   - ./sugar.d:/sugar.d

  links:
   - oracle
   - elastic
   - redis
  
  environment:
   - DB_USER=sugar
   - DB_PASS=sugar
   - SUGAR_LICENSE=
   - SUGAR_DB_TYPE=oci8
   - ORACLE_SERVICE=orcl
   - SUGAR_HOST=sugar.sugar.docker

oracle:
  image: absolutapps/oracle-12c-ee

  volumes:
   - ./oradata:/u01/app/oracle
   - ./oracle.d:/oracle.init.d

  expose:
   - "1521"
   - "8080"

  ports:
   - "1521:1521"
   - "8080:8080"    

  privileged: true

elastic:
  image: elasticsearch:1.4

  volumes:
  - ./elastic:/usr/share/elasticsearch/data

redis:
  image: redis
  
  volumes:
   - ./redis:/data